package com.unuslumen.app.domain.model

import kotlinx.serialization.Serializable

/**
 * Types of thought cycle triggers.
 */
enum class ThoughtTriggerType(val displayName: String, val description: String) {
    SCHEDULED("Scheduled", "Run on a schedule (e.g., daily reflection)"),
    EVENT("Event-based", "Run when specific events occur"),
    THRESHOLD("Threshold-based", "Run when metrics cross thresholds")
}

/**
 * Types of thought cycle outputs.
 */
enum class ThoughtOutputType(val displayName: String, val description: String) {
    INSIGHT("Insight", "Generate insights about patterns or anomalies"),
    ACTION("Action", "Propose or execute actions"),
    MEMORY("Memory", "Create or update memory facts"),
    PROPOSAL("Proposal", "Propose changes to prompts, tools, or skills")
}

/**
 * Types of insights.
 */
enum class InsightType(val displayName: String, val description: String) {
    PATTERN("Pattern", "Recurring pattern detected"),
    ANOMALY("Anomaly", "Unusual behavior detected"),
    SUGGESTION("Suggestion", "Improvement suggestion"),
    PREDICTION("Prediction", "Predicted future state")
}

/**
 * Configuration for scheduled thought cycles.
 */
@Serializable
data class ScheduledThoughtConfig(
    val intervalMs: Long,        // Run interval
    val initialDelayMs: Long = 0
)

/**
 * Configuration for event-based thought cycles.
 */
@Serializable
data class EventThoughtConfig(
    val eventTypes: List<String>, // Events that trigger this cycle
    val debounceMs: Long = 0      // Debounce time
)

/**
 * Configuration for threshold-based thought cycles.
 */
@Serializable
data class ThresholdThoughtConfig(
    val metric: String,          // Metric to monitor
    val operator: String,         // gt, lt, gte, lte, eq
    val value: Double,           // Threshold value
    val cooldownMs: Long = 0     // Cooldown before re-triggering
)

/**
 * A thought process step.
 */
@Serializable
data class ThoughtStep(
    val type: String,            // ANALYZE, REFLECT, SYNTHESIZE, PROPOSE
    val input: String,           // What to analyze/reflect on
    val params: Map<String, String> = emptyMap()
)

/**
 * A thought cycle definition.
 */
@Serializable
data class GuruThoughtCycle(
    val id: String,
    val name: String,
    val displayName: String,
    val description: String,
    val triggerType: ThoughtTriggerType,
    val triggerConfig: String,
    val thoughtProcess: List<ThoughtStep>,
    val outputType: ThoughtOutputType,
    val outputConfig: String?,
    val enabled: Boolean,
    val createdAt: Long,
    val lastRunAt: Long?,
    val lastResult: String?,
    val runCount: Int,
    val insightCount: Int,
    val actionCount: Int,
    val proposalCount: Int
)

/**
 * An insight generated by a thought cycle.
 */
@Serializable
data class GuruInsight(
    val id: String,
    val cycleId: String,
    val cycleName: String,
    val type: InsightType,
    val title: String,
    val content: String,
    val confidence: Float,
    val source: String,
    val actionable: Boolean,
    val actionTaken: Boolean,
    val actionType: String?,
    val actionId: String?,
    val createdAt: Long,
    val acknowledgedAt: Long?,
    val dismissedAt: Long?
)

/**
 * Request to create a thought cycle.
 */
@Serializable
data class CreateThoughtCycleRequest(
    val name: String,
    val displayName: String,
    val description: String,
    val triggerType: ThoughtTriggerType,
    val triggerConfig: String,
    val thoughtProcess: List<ThoughtStep>,
    val outputType: ThoughtOutputType,
    val outputConfig: String?
)

/**
 * Result of thought cycle execution.
 */
@Serializable
data class ThoughtCycleResult(
    val cycleId: String,
    val cycleName: String,
    val startedAt: Long,
    val completedAt: Long,
    val success: Boolean,
    val insights: List<GuruInsight>,
    val actions: List<String>,
    val proposals: List<String>,
    val error: String?,
    val executionTimeMs: Long
)

/**
 * Summary of thought cycles.
 */
@Serializable
data class ThoughtCyclesSummary(
    val totalCycles: Int,
    val enabledCycles: Int,
    val scheduledCycles: Int,
    val eventCycles: Int,
    val thresholdCycles: Int,
    val totalRuns: Int,
    val totalInsights: Int,
    val totalActions: Int,
    val totalProposals: Int,
    val unacknowledgedInsights: Int
)