package com.unuslumen.app.data.tools

import com.unuslumen.app.data.tools.registry.ToolDefinition
import com.unuslumen.app.data.tools.registry.ToolExecutor
import com.unuslumen.app.data.tools.registry.ToolParameter
import com.unuslumen.app.data.tools.registry.ToolParameterType
import com.unuslumen.app.data.tools.registry.ToolResultExtractor
import com.unuslumen.app.data.tools.registry.ToolSetRegistration
import kotlin.reflect.KClass

object ClipboardToolDefinitions : ToolSetRegistration {

    const val GET_CLIPBOARD = "getClipboard"
    const val SET_CLIPBOARD = "setClipboard"
    const val CLEAR_CLIPBOARD = "clearClipboard"

    override val definitions = listOf(
        ToolDefinition(
            name = GET_CLIPBOARD,
            description = "Read the current text from the system clipboard. Use when your human copies something and you want to grab it, or when you need to see what's on the clipboard.",
            category = "clipboard",
            parameters = emptyList(),
            permissions = emptyList()
        ),
        ToolDefinition(
            name = SET_CLIPBOARD,
            description = "Write text to the system clipboard. Use when you generate something and want your human to be able to paste it anywhere.",
            category = "clipboard",
            parameters = listOf(
                ToolParameter("text", ToolParameterType.String, required = true, description = "Text to put on the clipboard"),
                ToolParameter("label", ToolParameterType.String, required = false, description = "Label for the clipboard item, e.g. 'Generated by Guru'")
            ),
            permissions = emptyList()
        ),
        ToolDefinition(
            name = CLEAR_CLIPBOARD,
            description = "Clear the system clipboard.",
            category = "clipboard",
            parameters = emptyList(),
            permissions = emptyList()
        )
    )

    override fun executorClass(): KClass<out ToolExecutor> = ClipboardToolExecutor::class
    override fun extractorClass(): KClass<out ToolResultExtractor>? = null
}