package com.unuslumen.app.data.tools

import com.unuslumen.app.data.tools.registry.ToolDefinition
import com.unuslumen.app.data.tools.registry.ToolExecutor
import com.unuslumen.app.data.tools.registry.ToolParameter
import com.unuslumen.app.data.tools.registry.ToolParameterType
import com.unuslumen.app.data.tools.registry.ToolResultExtractor
import com.unuslumen.app.data.tools.registry.ToolSetRegistration
import kotlin.reflect.KClass

object ThoughtToolDefinitions : ToolSetRegistration {
    const val CREATE_THOUGHT_CYCLE = "createThoughtCycle"; const val LIST_THOUGHT_CYCLES = "listThoughtCycles"
    const val GET_THOUGHT_CYCLE = "getThoughtCycle"; const val EXECUTE_THOUGHT_CYCLE = "executeThoughtCycle"
    const val DELETE_THOUGHT_CYCLE = "deleteThoughtCycle"; const val ENABLE_THOUGHT_CYCLE = "enableThoughtCycle"
    const val DISABLE_THOUGHT_CYCLE = "disableThoughtCycle"; const val GET_INSIGHTS = "getInsights"
    const val ACKNOWLEDGE_INSIGHT = "acknowledgeInsight"; const val DISMISS_INSIGHT = "dismissInsight"

    override val definitions = listOf(
        ToolDefinition(name = CREATE_THOUGHT_CYCLE, description = "Create a thought cycle - a background reflection process for autonomous analysis, insights, and improvement.", category = "thought", parameters = listOf(ToolParameter("name", ToolParameterType.String, true, "Cycle name"), ToolParameter("displayName", ToolParameterType.String, true, "Display name"), ToolParameter("description", ToolParameterType.String, true, "Description"), ToolParameter("triggerType", ToolParameterType.String, true, "SCHEDULED, EVENT, or THRESHOLD"), ToolParameter("triggerConfig", ToolParameterType.String, true, "JSON trigger config"), ToolParameter("thoughtProcess", ToolParameterType.String, true, "JSON array of thought steps"), ToolParameter("outputType", ToolParameterType.String, true, "INSIGHT, ACTION, MEMORY, or PROPOSAL"), ToolParameter("outputConfig", ToolParameterType.String, false, "JSON output config")), permissions = emptyList()),
        ToolDefinition(name = LIST_THOUGHT_CYCLES, description = "List all thought cycles.", category = "thought", parameters = emptyList(), permissions = emptyList()),
        ToolDefinition(name = GET_THOUGHT_CYCLE, description = "Get detailed information about a specific thought cycle.", category = "thought", parameters = listOf(ToolParameter("name", ToolParameterType.String, true, "Cycle name or ID")), permissions = emptyList()),
        ToolDefinition(name = EXECUTE_THOUGHT_CYCLE, description = "Execute a thought cycle immediately. Runs the reflection process and generates insights.", category = "thought", parameters = listOf(ToolParameter("name", ToolParameterType.String, true, "Cycle name or ID")), permissions = emptyList()),
        ToolDefinition(name = DELETE_THOUGHT_CYCLE, description = "Delete a thought cycle and all associated insights.", category = "thought", parameters = listOf(ToolParameter("cycleId", ToolParameterType.String, true, "Cycle ID")), permissions = emptyList()),
        ToolDefinition(name = ENABLE_THOUGHT_CYCLE, description = "Enable a disabled thought cycle.", category = "thought", parameters = listOf(ToolParameter("cycleId", ToolParameterType.String, true, "Cycle ID")), permissions = emptyList()),
        ToolDefinition(name = DISABLE_THOUGHT_CYCLE, description = "Disable a thought cycle.", category = "thought", parameters = listOf(ToolParameter("cycleId", ToolParameterType.String, true, "Cycle ID")), permissions = emptyList()),
        ToolDefinition(name = GET_INSIGHTS, description = "Get all insights generated by thought cycles.", category = "thought", parameters = listOf(ToolParameter("type", ToolParameterType.String, false, "Filter by type: PATTERN, ANOMALY, SUGGESTION, PREDICTION"), ToolParameter("unacknowledgedOnly", ToolParameterType.Boolean, false, "Only unacknowledged")), permissions = emptyList()),
        ToolDefinition(name = ACKNOWLEDGE_INSIGHT, description = "Acknowledge an insight. Marks it as reviewed.", category = "thought", parameters = listOf(ToolParameter("insightId", ToolParameterType.String, true, "Insight ID")), permissions = emptyList()),
        ToolDefinition(name = DISMISS_INSIGHT, description = "Dismiss an insight. Marks it as not relevant.", category = "thought", parameters = listOf(ToolParameter("insightId", ToolParameterType.String, true, "Insight ID")), permissions = emptyList())
    )
    override fun executorClass(): KClass<out ToolExecutor> = ThoughtToolExecutor::class
    override fun extractorClass(): KClass<out ToolResultExtractor>? = null
}