package com.unuslumen.app.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an insight generated by a thought cycle.
 */
@Entity(
    tableName = "guru_insights",
    indices = [
        Index(value = ["cycleId"], name = "index_guru_insights_cycleId"),
        Index(value = ["createdAt"], name = "index_guru_insights_createdAt"),
        Index(value = ["type"], name = "index_guru_insights_type")
    ]
)
data class GuruInsightEntity(
    @PrimaryKey
    val id: String,
    val cycleId: String,
    val type: String, // PATTERN, ANOMALY, SUGGESTION, PREDICTION
    val title: String,
    val content: String,
    val confidence: Float,
    val source: String, // JSON source data references
    @ColumnInfo(defaultValue = "0")
    val actionable: Boolean = false,
    @ColumnInfo(defaultValue = "0")
    val actionTaken: Boolean = false,
    val actionType: String? = null,
    val actionId: String? = null,
    val createdAt: Long,
    val acknowledgedAt: Long? = null,
    val dismissedAt: Long? = null
)