# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.kts.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-if @kotlinx.serialization.Serializable class **
-keep class <1> {
    *;
}
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}
-if @kotlinx.serialization.Serializable class ** {
    static **$* *;
}
-keepclassmembers class <2>$<3> {
    kotlinx.serialization.KSerializer serializer(...);
}
-if @kotlinx.serialization.Serializable class ** {
    public static ** INSTANCE;
}
-keepclassmembers class <1> {
    public static <1> INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}
-keep class com.unuslumen.app.widget.** { *; }

-keep class * extends ai.koog.agents.core.tools.reflect.ToolSet { *; }

-keep enum * { *; }


-keepattributes RuntimeVisibleAnnotations,AnnotationDefault,MethodParameters

-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
-dontwarn org.slf4j.impl.**
-dontwarn brave.**
-dontwarn com.aayushatharva.brotli4j.**
-dontwarn com.google.auto.value.**
-dontwarn io.micrometer.**
-dontwarn io.netty.**
-dontwarn io.reactivex.**
-dontwarn javax.enterprise.**
-dontwarn org.LatencyUtils.**
-dontwarn org.apache.log4j.**
-dontwarn org.apache.logging.log4j.**
-dontwarn reactor.blockhound.**
-dontwarn rx.**

# Tor (tor-android) native library
-keep class org.torproject.jni.** { *; }
-keep class info.guardianproject.tor.** { *; }

# Vosk speech + its JNA transport. Both are JNI-bound by name: libjnidispatch.so
# resolves Native.initIDs / Pointer.peer and libvosk.so calls LibVosk members via
# fixed symbol + field names at runtime. R8 obfuscation renames them (peer -> m)
# and the native link dies with "Can't obtain peer field ID for class
# com.sun.jna.Pointer" -> NoClassDefFoundError org.vosk.LibVosk on first use
# (production v3.6.0 video-send crash). Keep every original name.
-keep class com.sun.jna.** { *; }
-keep class org.vosk.** { *; }
-keep class net.java.dev.jna.** { *; }
-dontwarn com.sun.jna.**
-dontwarn org.vosk.**
# Belt and braces: pin the exact JNI-looked-up members even if the broad
# package keeps above ever get narrowed. These are the symbols
# libjnidispatch.so resolves by hardcoded string in initIDs().
-keepclassmembers class com.sun.jna.Pointer {
    protected long peer;
}
-keepclassmembers class com.sun.jna.Native {
    private static native void initIDs();
    private static native int sizeof(int);
    private static native java.lang.String getNativeVersion();
    private static native java.lang.String getAPIChecksum();
    private static native long _getDirectBufferPointer(java.nio.Buffer);
    private static native void unregister(java.lang.Class, long[]);
    java.lang.Object fromNative(java.lang.reflect.Method, java.lang.Object);
    static java.lang.Object toNative(com.sun.jna.ToNativeConverter, java.lang.Object);
    static java.lang.Object fromNative(com.sun.jna.FromNativeConverter, java.lang.Object, java.lang.reflect.Method);
    private static native java.lang.Class nativeType(java.lang.Class);
    private static native java.lang.Object invokeStructure(com.sun.jna.Function, long, int, java.lang.Object[], long, long);
    static void dispose();
}
-keepclassmembers class org.vosk.LibVosk { *; }
-keep class com.sun.jna.Structure { *; }
-keep class com.sun.jna.internal.* { *; }
-keep class com.sun.jna.ptr.** { *; }
-keepclasseswithmembernames class com.sun.jna.Native$** { *; }
# Vosk native layer binds Java side helpers by name too
-keep class org.vosk.android.** { *; }

# --- R8 missing-class suppressions (generated by AGP missing_rules.txt, release build 2026-09-26) ---
# JVM-only optional paths of bundled libraries: references compile but these
# classes never resolve on Android, safe to warn-suppress.
-dontwarn com.fasterxml.jackson.core.JsonFactory
-dontwarn com.fasterxml.jackson.core.JsonGenerator
-dontwarn io.opentelemetry.api.incubator.logs.ExtendedLogger
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedDoubleHistogram
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedDoubleHistogramBuilder
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongCounter
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongCounterBuilder
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongUpDownCounter
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongUpDownCounterBuilder
-dontwarn io.opentelemetry.api.incubator.trace.ExtendedSpanBuilder
-dontwarn io.opentelemetry.api.incubator.trace.ExtendedTracer
-dontwarn java.lang.ProcessHandle
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn jdk.jfr.Event
-dontwarn jdk.net.ExtendedSocketOptions
-dontwarn org.HdrHistogram.AbstractHistogram
-dontwarn org.HdrHistogram.Histogram