# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.kts.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile
-if @kotlinx.serialization.Serializable class **
-keep class <1> {
    *;
}
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
    static <1>$Companion Companion;
}
-if @kotlinx.serialization.Serializable class ** {
    static **$* *;
}
-keepclassmembers class <2>$<3> {
    kotlinx.serialization.KSerializer serializer(...);
}
-if @kotlinx.serialization.Serializable class ** {
    public static ** INSTANCE;
}
-keepclassmembers class <1> {
    public static <1> INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}
-keep class com.unuslumen.app.widget.** { *; }

-keep class * extends ai.koog.agents.core.tools.reflect.ToolSet { *; }

-keep enum * { *; }


-keepattributes RuntimeVisibleAnnotations,AnnotationDefault,MethodParameters

-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn org.openjsse.**
-dontwarn org.slf4j.impl.**
-dontwarn brave.**
-dontwarn com.aayushatharva.brotli4j.**
-dontwarn com.google.auto.value.**
-dontwarn io.micrometer.**
-dontwarn io.netty.**
-dontwarn io.reactivex.**
-dontwarn javax.enterprise.**
-dontwarn org.LatencyUtils.**
-dontwarn org.apache.log4j.**
-dontwarn org.apache.logging.log4j.**
-dontwarn reactor.blockhound.**
-dontwarn rx.**

# Tor (tor-android) native library
-keep class org.torproject.jni.** { *; }
-keep class info.guardianproject.tor.** { *; }

# --- R8 missing-class suppressions (generated by AGP missing_rules.txt, release build 2026-09-26) ---
# JVM-only optional paths of bundled libraries: references compile but these
# classes never resolve on Android, safe to warn-suppress.
-dontwarn com.fasterxml.jackson.core.JsonFactory
-dontwarn com.fasterxml.jackson.core.JsonGenerator
-dontwarn io.opentelemetry.api.incubator.logs.ExtendedLogger
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedDoubleHistogram
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedDoubleHistogramBuilder
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongCounter
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongCounterBuilder
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongUpDownCounter
-dontwarn io.opentelemetry.api.incubator.metrics.ExtendedLongUpDownCounterBuilder
-dontwarn io.opentelemetry.api.incubator.trace.ExtendedSpanBuilder
-dontwarn io.opentelemetry.api.incubator.trace.ExtendedTracer
-dontwarn java.lang.ProcessHandle
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn jdk.jfr.Event
-dontwarn jdk.net.ExtendedSocketOptions
-dontwarn org.HdrHistogram.AbstractHistogram
-dontwarn org.HdrHistogram.Histogram